# Generated by Django 5.1.7 on 2025-04-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cart_provider_servercomment_user_server_provider_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ram',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='ghz',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
